name: IITM Assignment CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Required Step 1: Your Email
      - name: 23f2003863@ds.study.iitm.ac.in
        run: echo "Starting workflow for Sachin Jha"

      # Required Step 2: The Cache
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f0b8518

      # Required Step 3: Echo the hit/miss
      - name: prime-cache-f0b8518
        run: echo "Cache hit status is ${{ steps.cache-step.outputs.cache-hit }}"
